version: '3'

services:
  postgres:
    image: 'postgres:15'
    container_name: 'java-postgres'
    ports:
      - 5433:5432
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=postgres'
