spring:
  data:
    mongodb:
      database: application_db
      host: localhost
      port: 27018

  sql:
    init:
      mode: always
      schema-locations: schema.sql
      data-locations: data.sql

  datasource:
    url: jdbc:mongodb://localhost:27018/application_db
    driver-class-name: 'mongodb.jdbc.MongoDriver'
    username:
    password:
