spring:
  data:
    mongodb:
      database: application_db
      host: localhost
      port: 27018
      uri: mongodb://localhost:27018/application_db

mongock:
  enabled: true
  change-logs-scan-package: org.example.hw_8.config
  legacy-migration:
    collection-name: dbchangelog


