spring:
  datasource:
    url: jdbc:h2:mem:maindb
    username: admin
    password: admin
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true

  sql:
    init:
      mode: always
      schema-locations: schema.sql
      data-locations: data.sql

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

server:
  port: 8089
