spring:
  datasource:
    url: jdbc:h2:mem:maindb
    username: admin
    password: admin

  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql
  h2:
    console:
      enabled: true
      path: /h2-console

#  flyway:
#    user: admin
#    password: admin
#    url: jdbc:h2:mem:maindb
#    schemas: PUBLIC
#    locations: filesystem:db.migration
#    enabled: true

server:
  port: 8089