name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-app:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'
          postgresql db: postgres
          postgresql schema: hw_9
          postgresql user: admin
          postgresql password:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build application
        run: |
          mvn verify --no-transfer-progress
