name: Build

on:
  pull_request:

jobs:
  build-app:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD=admin
          POSTGRES_SCHEMA=hw_9
        ports:
          - "5433:5432"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build application
        run: |
          mvn verify --no-transfer-progress
